### ISSUE TITLE
Homepage link in "About" box, is broken (Windows).

### ISSUE THREAD

**Issue by Achaean** [otsaloma/nfoview#14]
V1.23 installed on Win 10 x64 v.10.0.15063.
Workaround: Right click -> "Copy Link Address" -> paste in browser.

Sidequestion: 32-bit apps aren't so stable on 64 Windows. Is it possible to compile it as native 64 app? How?

**Comment by otsaloma** [comment]
That's a bug in the version of the GTK+ toolkit used, link buttons don't work on Windows. I expect that will be fixed in GTK+ in time, or might be already in a newer version.

64-bit compilation might be possible, it's not really about nfoview, but about the dependencies. I don't remember if there are 64-bit versions of Windows binaries of dependencies available, but can check next time when building.

What do you mean by 32-bit apps being unstable?

**Comment by Achaean** [comment]
Oh...I see!
Then we'll wait, for the GTK+ bugfix. :-)

For the need of x64 binaries, I meant that running x32 apps on Win64, means that they'll run through WOW64 and for telling you the truth, I was never entirely trusted the compatibility layers.
WOW64 is what NTVDM was for previous Windows releases. Although it's a must, it lucks behind, in terms of performance and stability.
Anyway! Just an optional feature request. Nothing of great importance!

Happy Holiday Season!!! :-)
G.

**Comment by otsaloma** [comment]
OK, will keep the 64-bit in mind. Happy Holidays!
